### ISSUE TITLE
2. Split introduction slides

### ISSUE THREAD

**Issue by AestheticAkhmad** [memo1918/visualNovelDSP341#4]
Split each introduction slide into number of sub-slides based on the number of sentences in the text.

For example:
Text is: 
" Fist sentence. Second sentence. Third sentence. Fourth sentence.". Currently we have a slide with this whole text.

It has to be split in this way:
Slide 1:
"First sentence."
Slide 2:
"First sentence. Second sentence."
Slide 3:
"First sentence. Second sentence. Third sentence."
Slide 4:
"First sentence. Second sentence. Third sentence. Fourth sentence."

**Comment by mertgulmus** [comment]
I will be working on this.

**Comment by mertgulmus** [comment]
- need background images, only one of them is present in the repo
- need the name of the font used

**Comment by AestheticAkhmad** [comment]
Need pictures.
