### ISSUE TITLE
3. Remake settlement slide in Introduction

### ISSUE THREAD

**Issue by AestheticAkhmad** [memo1918/visualNovelDSP341#5]
Currently, we have the Settlement image with 7 variations of building highlighting (red color). 
This needs to be changed (using AI generated settlement images). 

1. First image should be normal image of settlement with added text "The Settlement".
2. The next seven images will be the variants of the first image but everything should be dark except for the highlighted building.
For example: the hospital. And the description should be in the bottom as text.

**Comment by RustamRahimov** [comment]
Done
