### ISSUE TITLE
5. Remove the scores after questions selection

### ISSUE THREAD

**Issue by AestheticAkhmad** [memo1918/visualNovelDSP341#7]
There are currently texts appear after choosing each question which state how many points you got. 
Example: "-2, hostile approach".

This must not appear for the player, since this is used only for the calculation of the result of the interview.
This score is used for logic and validation of results of the interview after each question round.
If the total score is less than -5, then interview is failed. Else if it is greater than 10 then the interview is successful.

**Comment by RustamRahimov** [comment]
Done
